apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: damigah/devops:latest # This will be pulled from my Docker Hub repository.
        ports:
        - containerPort: 5000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP # known Transmission Control Protocol, is a core protocol of the Internet Protocol (IP) suite. 
      port: 80      # It provides a reliable connection-oriented communication service between two devices on a network.
      targetPort: 5000
  type: ClusterIP